repos:
-   repo: local
    hooks:
    -   id: tox-format
        name: Formatting
        entry: tox -e format
        language: system
        types: [python]
        pass_filenames: false
    -   id: tox-lint
        name: Linting
        entry: tox -e lint
        language: system
        types: [python]
        pass_filenames: false
    -   id: tox-test
        name: Unit Tests
        entry: tox -e test
        language: system
        types: [python]
        pass_filenames: false